python automatic_training.py -o N16 -m /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/HackerRF/BASELINE/best_checkpoint.h5 -v -CP True -rp /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/l2/l2_idx.csv -CPP /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/AUTOMATIC/N16/1-pr.csv
python automatic_training.py -o N32 -m /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/HackerRF/BASELINE/best_checkpoint.h5 -v -CP True -rp /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/l2/l2_idx.csv -CPP /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/AUTOMATIC/N32/1-pr.csv
python automatic_training.py -o N64 -m /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/HackerRF/BASELINE/best_checkpoint.h5 -v -CP True -rp /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/l2/l2_idx.csv -CPP /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/AUTOMATIC/N64/1-pr.csv
#python automatic_training.py -o N2 -m /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/HackerRF/BASELINE/best_checkpoint.h5 -v -CP True -rp /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/l2/l2_idx.csv -CPP /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/AUTOMATIC/N2/1-pr.csv
#python automatic_training.py -o N2 -m /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/HackerRF/BASELINE/best_checkpoint.h5 -v -CP True -rp /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/l2/l2_idx.csv -CPP /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/AUTOMATIC/N2/1-pr.csv



#python automatic_training.py -o N2 -m /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/HackerRF/BASELINE/best_checkpoint.h5 -v -CP True -rp /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/l2/l2_idx.csv -CPP /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/AUTOMATIC/N2/1-pr.csv
#python automatic_training.py -o N4 -m /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/HackerRF/BASELINE/best_checkpoint.h5 -v -CP True -rp /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/l2/l2_idx.csv -CPP /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/AUTOMATIC/N4/1-pr.csv
#python automatic_training.py -o N8 -m /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/HackerRF/BASELINE/best_checkpoint.h5 -v -CP True -rp /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/l2/l2_idx.csv -CPP /home/mabon/codebase/TinyRadio/RFP/experiments/ResNet/NEU/SCORES/AUTOMATIC/N8/1-pr.csv
